apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arg-workflow-demo
spec:
  entrypoint: dataload

  volumes: 
   - name: dir
     persistentVolumeClaim:
      claimName: my-pvc-argo 
  
  arguments:
    parameters:
    - name: directory
      value: 'data'

  templates:
    - name: dataload
      container:
        image: tarun0/argo:omanshu
        command: [python3, /tmp/loading.py, '{{inputs.parameters.directory}}']
        volumeMounts:
          - name: dir
            mountPath: /tmp
      inputs:
        parameters:
          - name: directory
            value: 'data'