apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-pvc-1 
  labels:
    app: demo4
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
