apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arg-workflow-demo
spec:
  entrypoint: start

  volumes: 
   - name: dir
     persistentVolumeClaim:
      claimName: my-pvc-argo 
  
  arguments:
    parameters:
    - name: directory
      value: '/tmp/data'

  templates:
    - name: start
      dag:
        tasks:
        - name : dataload
          template: dataload
          
        - name: train
          dependencies: [dataload]
          template: training
          
    - name: dataload
      container:
        image: tarun0/argo:v2
        command: [python3, /tmp/loading1.py, '{{inputs.parameters.directory}}']
        volumeMounts:
          - name: dir
            mountPath: /tmp
      inputs:
        parameters:
          - name: directory
            value: '/tmp/data'

    - name: training
      container:
        image: tarun0/argo:v2
        command: [python3, /tmp/training1.py, '{{inputs.parameters.directory}}']
        volumeMounts:
          - name: dir
            mountPath: /tmp
      inputs:
        parameters:
          - name: directory
            value: '/tmp/data'
